name: test

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11"]
        poetry-version: [ "latest" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: test
        run: poetry install --with dev && make test